### PR TITLE
Fix TypeError in ImageModal when file does not exist

### LINKED ISSUE #71: TypeError in ImageModal when file doesn't exist (onImageBeforeProduceHTML)
## Setup

- MediaWiki 1.43 (REL1_43)
- BootstrapComponents ~5 (latest via Composer)
- PHP 8.x

When `$wgBootstrapComponentsModalReplaceImageTag` is enabled and a wiki page references a non-existent file (e.g. `[[File:Missing.png]]`), the `onImageBeforeProduceHTML` hook crashes with:

```
TypeError: MediaWiki\Extension\BootstrapComponents\ImageModal::__construct():
Argument #3 ($file) must be of type File, bool given,
called in .../extensions/BootstrapComponents/src/HooksHandler.php on line 146
```
## Cause

MediaWiki's `ImageBeforeProduceHTML` hook passes `File|false` for the `$file` parameter. When the file doesn't exist, `$file` is `false`. `HooksHandler::onImageBeforeProduceHTML()` passes this directly to `new ImageModal(...)`, but `ImageModal::__construct()` has a strict `File` type hint on argument #3.

## Suggested fix

Add a guard in `HooksHandler.php` before constructing `ImageModal`:

```php
if ( !$file ) {
    return true;
}
```

This skips the modal (there's nothing to display) and lets MediaWiki render its normal missing-file link.

Until a fix is merged, set `$wgBootstrapComponentsModalReplaceImageTag` to "false".

### PR DESCRIPTION
**Pull request by kghbln**
## Summary

- When `$wgBootstrapComponentsModalReplaceImageTag` is enabled and a page references a non-existent file, `onImageBeforeProduceHTML` passes `false` for `$file` to `ImageModal::__construct()`, which has a strict `File` type hint → TypeError
- Adds a guard to skip modal replacement when `$file` is `false`, letting MediaWiki render its normal missing-file link

Fixes #71

### CODE REVIEW

File: src/HooksHandler.php [hunk 1]
```diff
@@ -140,6 +140,9 @@ public function onImageBeforeProduceHTML(
 	): bool {
 		if ( $this->getConfig()->has( 'BootstrapComponentsModalReplaceImageTag' ) &&
 			$this->getConfig()->get( 'BootstrapComponentsModalReplaceImageTag' ) ) {
+			if ( !$file ) {
```
Comment (malberts) [inline src/HooksHandler.php:143]: This guard clause can be the first statement, before the existing `if`.
Better to test explicitly: `$file === false`
And the docstring is wrong. But that's for another day.
